version: "3"

services:
  postgres-sorteio:
    container_name: postgres-sorteio
    image: postgres:11.2-alpine
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sorteio
    restart: always
    shm_size: "256mb"
    ports:
      - 5432:5432

  front-sorteio:
    container_name: front-sorteio
    image: paice0510/front-sorteio
    ports:
      - 3000:80

  api-sorteio:
    container_name: api-sorteio
    image: paice0510/api-sorteio
    ports:
      - 3333:3333
